---
title: "git_01"
author: "Math_116"
date: "Fall semester"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
A BOAT, beneath a sunny sky  
Lingering onward dreamily  
In an evening of July--    
 
Children three that nestle near,  
Eager eye and willing ear,   

<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

## Second Verse
Some say the world will end in fire,  
Some say in ice.  
From what I’ve tasted of desire  
I hold with those who favour fire.  
But if it had to perish twice,	

<!--Put the first five lines of a poem by Robert Frost here!-->

## Third Verse
"The sun was shining on the sea,   
      Shining with all his might:   
He did his very best to make   
      The billows smooth and bright —   
And this was odd, because it was   
      The middle of the night.   

The moon was shining sulkily,   
      Because she thought the sun   
Had got no business to be there   
      After the day was done —   
"It's very rude of him," she said,   
      "To come and spoil the fun."

<!--Put the first two verses of The Walrus and the Carpenter here!-->

## Last Verse
Always and forever is so far away,   
But know I'll stand by you for every last day,   

Your beauty shines like a warming ray  
That keeps me from ever falling astray,   

Our love is strong and here to stay.  
Hold onto us and we'll find a new way,   

One that won't have any gray,   
Only love that will never fray...   

Always and forever, Baby  

<!--Put a short poem of your choice 8-20 lines,here!-->
